export const COLORS = Object.freeze({
  // LIGHT: {
  PRIMARY: "#ff6767",
  MAIN: "#fff",
  SELECT_BG: "#f7f9fc",
  BORDER: "#eee",
  ICON: "gray",
  CALL_BTN: "#7ED09E",
  TOUCHABLE_TEXT: "#6979F8",
  DRAWER_TEXT: "#585858",
  TEXT: "#152222",
  TITLE: "#fff",
  CARD_BG: "#F5F7FB",
  // },
  // DARK: {
  //   PRIMARY: "#ff6767",
  //   MAIN: "#fff",
  //   SELECT_BG: "#f7f9fc",
  //   BORDER: "#eee",
  //   ICON: "gray",
  //   CALL_BTN: "7ED09E",
  //   TOUCHABLE_TEXT: "#6979F8",
  //   DRAWER_TEXT: "#585858",
  //   TEXT: "#152222",
  //   TITLE: "#fff",
  //   CARD_BG: "#F5F7FB",
  // },
});
